# TG48M-P Platform 

TG48MP_VERSION=1.0

export TG48MP_VERSION

TG48M-P_PLATFORM = sonic-platform-tg48m-p_$(TG48MP_VERSION)_$(CONFIGURED_ARCH).deb
$(TG48M-P_PLATFORM)_SRC_PATH = $(PLATFORM_PATH)/sonic-platform-tg48m-p
$(TG48M-P_PLATFORM)_DEPENDS += $(LINUX_HEADERS) $(LINUX_HEADERS_COMMON)
$(TG48M-P_PLATFORM)_PLATFORM = arm64-delta_tg48m_poe-r0

SONIC_DPKG_DEBS += $(TG48M-P_PLATFORM)
